[build]
  base = "project"
  command = "npm run build"
  publish = "dist"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_ANON_KEY,VITE_SUPABASE_URL,VITE_GOOGLE_MAPS_API_KEY"

# Redirection SPA (React Router ou Vite SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


